print("hello world")
print("this is a jenkins integration file to test my integrations are working or not")
print("testing build targets poll scm with every minute automated building")
print("changing the file again to understand scm poll")
print("this line is created to fail a build job to get the email notifications from jenkins to gmail)
